services:
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    container_name: 'postgress'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha-backend
    ports:
      - "5432:5432"
    #volumes:
      #- ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
    networks:
      - rede-backend

networks:
  rede-backend:
    driver: bridge
