services:
  api01: &api
    image: rinha-backend-2024-q1:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"
    networks:
      - rede-backend

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"
    networks:
      - rede-backend
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"
    networks:
     - rede-backend

  db:
    image: postgres:latest
    hostname: db
    container_name: 'postgress'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha-backend
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
    command: "postgres -c synchronous_commit=0 -c full_page_writes=0"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "320MB"
    networks:
      - rede-backend

networks:
  rede-backend:
    driver: bridge
