CREATE TABLE IF NOT EXISTS CLIENT
(
    IDT_CLIENT    NUMERIC NOT NULL PRIMARY KEY,
    BALANCE      NUMERIC,
    CREDIT_LIMIT NUMERIC,
    NAME         VARCHAR(50)
);

CREATE SEQUENCE transaction_id_sequence INCREMENT BY 50;
CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    ID          BIGINT DEFAULT nextval('transaction_id_sequence'::regclass) PRIMARY KEY,
    AMOUNT      NUMERIC         NOT NULL,
    CREATED_AT  TIMESTAMP(6)    WITH TIME ZONE,
    DESCRIPTION VARCHAR(10)     NOT NULL,
    TYPE        CHAR(10)         NOT NULL,
    IDT_CLIENT   NUMERIC         NOT NULL
);

DO
$$
    BEGIN
        INSERT INTO CLIENT (IDT_CLIENT, NAME, CREDIT_LIMIT, BALANCE)
        VALUES (1, 'O BARATO SAI CARO', 1000 * 100, 0),
               (2, 'ZAN CORP LTDA', 800 * 100, 0),
               (3, 'LES CRUDERS', 10000 * 100, 0),
               (4, 'PADARIA JOIA DE COCAIA', 100000 * 100, 0),
               (5, 'KID MAIS', 5000 * 100, 0);
    END;
$$;

CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_CLIENT_ID_CREATED_AT ON TRANSACTIONS (IDT_CLIENT, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_CLIENT_ID ON TRANSACTIONS (IDT_CLIENT);

ALTER SYSTEM SET max_connections = '50';
SELECT pg_reload_conf();

